### ISSUE TITLE
Compatibility issue with September 2nd update

### ISSUE THREAD

**Issue by LWTechGaming** [cosmicsalad/Discord-Themes-and-Plugins#13]
Today a minor update to the Discord client was released. This causes this theme to not affect certain parts of a user's profile (See attachement below) and some parts to still be rendered as classic Discord themed parts.

![misrendered](https://cloud.githubusercontent.com/assets/18148938/18193451/720ffe5e-70e6-11e6-95ee-84bcc3f4c83d.png)

**Comment by ganon11000** [comment]
Can confirm I too am getting this ![issue](https://direct.ganon11000.co.uk/Pics/Discord_2016-09-04_19-49-41.png)

**Comment by cosmicsalad** [comment]
Yo @LWTechGaming @ganon11000  thanks for pointing this out, this issue should be fixed now. Just pushed out v1.5 :) Update and let me know if this is resolved
