### ISSUE TITLE
Drop down menu next to server cut off

### ISSUE THREAD

**Issue by silphy** [cosmicsalad/Discord-Themes-and-Plugins#14]
When I click the menu next to a server name, it looks like 
![with theme](https://cloud.githubusercontent.com/assets/22184374/18496792/d93cc8b4-79f6-11e6-8e65-bdef3b6a1fb0.png)
when it should look like this 
![normal](https://cloud.githubusercontent.com/assets/22184374/18496796/e3418c6e-79f6-11e6-8624-35105d31583f.png)

**Comment by shinji257** [comment]
It's much worse for me.  I don't even get the first option fully (cuts off half-way in).  There are some other themes affected as well so I'm going to poke at it with the inspector and see if I can figure it out.

**Comment by shinji257** [comment]
I think this looks better now. ;)

![image](https://cloud.githubusercontent.com/assets/261005/18779836/aa333b12-8148-11e6-939b-6da0bc3eea8e.png)
