### ISSUE TITLE
Request compatibility for September 27th update

### ISSUE THREAD

**Issue by LWTechGaming** [cosmicsalad/Discord-Themes-and-Plugins#16]
The server dropdown menu changed and a new user presence menu was added as shown in the screenshots below.

![Status menu](https://s22.postimg.org/86mskezmp/newmenu1.png)
![Server menu](https://s22.postimg.org/4bjehuggx/newmenu2.png)

Not high profile, but good to have maybe 😄

**Comment by SWooshs** [comment]
We need this please.

**Comment by cosmicsalad** [comment]
Got it covered, sorry for the delay on this update. Pushing the change in a sec ✌️

**Comment by LWTechGaming** [comment]
Cheers lad @cosmicsalad :ok_hand:

**Comment by cosmicsalad** [comment]
Should be good now 😄 Let me know if I'm missing anything
