### ISSUE TITLE
Profile image viewport too wide

### ISSUE THREAD

**Issue by LWTechGaming** [cosmicsalad/Discord-Themes-and-Plugins#17]
The profile image boundaries don't cut the profile picture off where it should and make it a circle, but instead stay as a square. Demonstrated below.

![PFP](https://i.imgur.com/jRL1JYH.png)

**Comment by LWTechGaming** [comment]
Besides, this issue was introduced fairly recently. Could be due to the most recent update, could be something else.

**Comment by cosmicsalad** [comment]
Thanks for pointing this out, definitely was recent. They must be making some changes to the profile modal. But all is good now :) Pushed the update
