### ISSUE TITLE
Edit CSS to slightly increase font size of usernames?

### ISSUE THREAD

**Issue by Phoenix100k** [cosmicsalad/Discord-Themes-and-Plugins#19]
Hey there. Less of an issue, more of a question.

I figured out how to remove the font family since I like Discord's default font, and I figured out how to increase the size of the chat messages. What I can't seem to figure out is how to increase the size of usernames. Mind telling me which variable I need to edit? Thanks in advance!

**Comment by cosmicsalad** [comment]
Sure, add this to the Custom CSS portion of BetterDiscord's settings and change the value to whatever you need:
`.messages h2 .user-name {
    font-size: 0.85em !important;
}`

✌🏼
