### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by FANadeem98** [cosmicsalad/Discord-Themes-and-Plugins#2]
Sorry if I am doing this completely wrong, but what I did was put the css file in the themes folder, and now i get this message. https://gyazo.com/529bcfe6401043242c065400e6d1ddd2 I tried to just copy the code in the css file to the custom css section, but the image wouldn't show up. If you could tell how to apply the theme, that would be great.(sorry if you gave instructions, I must have missed them if you did put them XD)
Thanks

**Comment by cosmicsalad** [comment]
That seems odd. As long as you placed DarkMatter.css in %AppData%/BetterDiscord/themes, then refreshed Discord (ctrl+r), and enabled it in settings it should work. Do you have any other themes installed? Or plugins maybe?
