### ISSUE TITLE
Dark Matter doesn't display BG?

### ISSUE THREAD

**Issue by TheHeroBilly** [cosmicsalad/Discord-Themes-and-Plugins#21]
In a recent update your theme doesn't display Background images anymore, I tried both the css file and the custom css selection, but neither display the image.

**Comment by cosmicsalad** [comment]
I updated the theme yesterday to fix this. Make sure you use the latest version (1.5.2)

**Comment by TheHeroBilly** [comment]
So it has been, I guess I checked the status shortly before you updated it, as I checked it yesterday and it didn't change anything.

**Comment by cosmicsalad** [comment]
No problem ✌ Glad it's better now
