### ISSUE TITLE
New discord servers list format (as well as friends button in DM tab)

### ISSUE THREAD

**Issue by nermolov** [cosmicsalad/Discord-Themes-and-Plugins#25]
Just how the title states, see below image

![formatting issue](https://i.imgur.com/ru3Xswc.jpg)

**Comment by cursedcookies** [comment]
I'm also facing this issue (expect its not just this theme....all my themes are messed up now)

**Comment by cosmicsalad** [comment]
These issues should be all good now. Sorry it took so long, had a crazy couple months lately.
