### ISSUE TITLE
Replyer no longer working

### ISSUE THREAD

**Issue by CinnamonFreak** [cosmicsalad/Discord-Themes-and-Plugins#29]
Doesn't work in the new Discord version.

**Comment by yorai1212** [comment]
Same

**Comment by GenesisAria** [comment]
Can concur

**Comment by cosmicsalad** [comment]
Apologies on the lack of DM updates, I've been real busy with a lot of personal stuff at the moment. But I'll try to get an update out this week! Thanks for the reminder.

**Comment by cosmicsalad** [comment]
Merged the fix, replyer should be fixed now.
