### ISSUE TITLE
Deafen & Mute buttons

### ISSUE THREAD

**Issue by TobyMoose** [cosmicsalad/Discord-Themes-and-Plugins#3]
When I use this theme on the desktop app v0.2.6(JSv1.57) the three buttons are almost unreachable. 
https://gyazo.com/dc8fe389e5da4f1f5b4f5e3a2574f86b Picture of the problem. Great theme besides this issue!

**Comment by cosmicsalad** [comment]
Thanks for letting me know! I just updated the theme to be fully compatible with Minimal mode and Compact mode.
