### ISSUE TITLE
Most selectors broken in DarkMatter

### ISSUE THREAD

**Issue by nermolov** [cosmicsalad/Discord-Themes-and-Plugins#34]
A lot of css selectors have broken in DarkMattter as per a discord update, see screenshot:

![aaaa](https://user-images.githubusercontent.com/6175137/31747466-a71e79fa-b432-11e7-8a5a-3503c3271a08.png)

**Comment by nermolov** [comment]
Seemed to resolve itself, sorry!

**Comment by nermolov** [comment]
Used to temporarily be an issue in canary, resolved itself, and is now an issue in both canary and stable.

**Comment by JrFander** [comment]
Same.. It's happening to me too
