### ISSUE TITLE
Broken with October update 

### ISSUE THREAD

**Issue by Abyss1992** [cosmicsalad/Discord-Themes-and-Plugins#37]
Theme is broken with new title bar

**Comment by RyanBlue** [comment]
A temporary fix is to use the 'Theme Fixer' theme by xNightWulf with Dark Matter. Some things still aren't right, but for the most part it fixes it. I would also suggest using 'Revert title bar' to remove the new bar at the top.

[revertTitlebar.theme.css.txt](https://github.com/cosmicsalad/Discord-Themes-and-Plugins/files/1424452/revertTitlebar.theme.css.txt)

[ThemeFix.theme.css.txt](https://github.com/cosmicsalad/Discord-Themes-and-Plugins/files/1424451/ThemeFix.theme.css.txt)

**Comment by jeuv** [comment]
I made a hacky fix for it https://pastebin.com/nF0AJbAC. The code is not pretty, but it works, mostly. I am using the ThemeFixer RyanBlue linked, so you might have to install that as well. The image linked shows how the fix looks for me.
![image](https://user-images.githubusercontent.com/14892162/32150349-fa13d762-bd11-11e7-8eb4-20b0d24a784c.png)

**Comment by spy653** [comment]
I'm getting this, only just changed.

![image](https://user-images.githubusercontent.com/5083962/32325003-263d2450-bfc5-11e7-846f-3b4d21f1d1ac.png)

**Comment by SynthSy** [comment]
I did a hacky edit myself https://gist.github.com/SynthSy/d838cfaaada4c026a95f416b6be164d2

![image](https://user-images.githubusercontent.com/16493314/32796945-06a38e04-c925-11e7-8374-41ce37d2e304.png)
