### ISSUE TITLE
Messages that failed to send aren't marked in any way

### ISSUE THREAD

**Issue by ganon11000** [cosmicsalad/Discord-Themes-and-Plugins#5]
Messages that fail are not marked in red text like the default theme.
Example:

Wanted / Expected:

http://i.imgur.com/9Vk5ytG.png

What happens:

http://i.imgur.com/8uMtWKO.png

Is there a way to fix this?

**Comment by cosmicsalad** [comment]
Thanks for pointing this out! Somehow it got overlooked, uploading an updated fix for that now.
