### ISSUE TITLE
Permission Text

### ISSUE THREAD

**Issue by RussoHD** [cosmicsalad/Discord-Themes-and-Plugins#6]
When opening the Role Permissions for a text/voice channel, the permissions only show the check box with out what the box is for. 

What is shown:
https://i.gyazo.com/47fa588df1c43b8224ea1cfdb76f75fe.png

**Comment by ganon11000** [comment]
for me it shows but the coloring makes it hard to make out

http://i.imgur.com/B84Jdb8.png

same with channel descriptions

http://i.imgur.com/UachR8s.png

**Comment by cosmicsalad** [comment]
Have you guys made any modifications with Custom CSS? The text next to checkboxes in settings and channel descriptions should already be white. Make sure you've pulled the latest version of Dark Matter into your themes folder. I recently made a lot of changes to the settings box. :)

**Comment by cosmicsalad** [comment]
This is what mine currently looks like even if I don't have a background image and everything is really dark. http://i.imgur.com/z87tmZV.png The text here should already be white.

**Comment by cosmicsalad** [comment]
Make sure you're updated to version 1.4.1 of Dark Matter and things should look/work fine. Let me know if this problem still persists.

**Comment by RussoHD** [comment]
Yeah updated and everything. Text for it still black though. Nothing was touched straight from the css. paste. https://i.gyazo.com/c69378a23bec69c25383e039891caa16.png

**Comment by cosmicsalad** [comment]
@RussoHD are you by chance using Discord's light theme? I probably need to just make sure the text in settings is forced white in this case.

**Comment by ganon11000** [comment]
I'm using dark theme

**Comment by cosmicsalad** [comment]
@RussoHD @ganon11000 Should be fixed now! I was looking in the wrong place -_-
