### ISSUE TITLE
Reply button doesn't work with nicknames

### ISSUE THREAD

**Issue by ExileEditing** [cosmicsalad/Discord-Themes-and-Plugins#9]
My friends have all of our names nicknamed on their server and when clicking the reply button it only types the nickname without the full "ID" or whatever so they don't get the @ 

http://prntscr.com/bjecda , http://prntscr.com/bjecmy

What it should show: http://prntscr.com/bjecgl , http://prntscr.com/bjecl5

**Comment by LinkofHyrule89** [comment]
Yeah I'm having a similar problem it's @ing the name without actually tagging the person.

**Comment by cosmicsalad** [comment]
@ExileEditing @LinkofHyrule89 Pushed an update that fixes this issue. :)
